language: python

sudo: false
addons:
    apt:
        packages:
            - texlive-full
            - build-essential
            - enchant

python:
    - "2.7"

script:
    - make reqs
    - make
    - make test
