Point Values:
=============

..  csv-table::
    :header: Item, Points
    :widths: 25, 20

    Orientation Exam, 50
    Exams (3), 150 ea = 450
    Labs (10), 30 ea = 300
    Homework, 10 ea = 100
    Participation (by email), 100
    **Total**,1000

..  note::

    Since this is a distance class, I expect you to communicate with me by
    email on a regular basis. You should be asking questions when you need
    help. Please attach code you are working on in your email so I can see what
    you are up to.
