Required Text:
==============

..  image:: cosc1315_textbook.jpg
    :align: center
    :width: 250

..  csv-table::
    :header: "Author(s)","title","ISBN","Publisher"
    :widths: 10, 30, 15, 10

    "Gaddis","Starting Out With Programming Logic, C++","9781323187487","Pearson"

..  note::

    The textbook is a custom edition taken from these books:

        * Starting Out with Programming Logic and Design, 4th Edition, 
          by Tony Gaddis

        * Starting out with C++: From Control Structures through Objects, 
          Brief Edition, 8th Edition, by Tony Gaddis
